### ISSUE TITLE
Splitter_characters_grouper_search_step Parameter Tuning article header is over the layout

### ISSUE THREAD

**Issue by xeenhl** [b0noI/AIF2#189]
The header of folowing article on the site is over the site layout

http://aif.io/blog/2014/12/27/splitter-characters-grouper-search-step-parameter-tuning/

![2015-01-03 17 32 52](https://cloud.githubusercontent.com/assets/3415766/5602789/f1670970-936d-11e4-92b4-47cf77840cda.png)

**Comment by Marcon** [comment]
Closed in 35f673b7
There is no normal fixes for that issue cause browsers can't break words on undescores.
Better to avoid long words like Splitter_characters_grouper_search_step  in titles
